# typed: false
# frozen_string_literal: true

# Homebrew formula for Buildermark
#
# To use this formula directly (without a tap), install with:
#   brew install --formula ./buildermark.rb
#
# For tap-based distribution, this formula is auto-generated by GoReleaser
# and published to gelatinousdevelopment/homebrew-tap. End users install with:
#   brew tap gelatinousdevelopment/tap
#   brew install buildermark
#
# To update the SHA256 and URL below after a new release, run:
#   apps/homebrew/package.sh <version>

class Buildermark < Formula
  desc "Rate and review coding agent developer workflows"
  homepage "https://github.com/gelatinousdevelopment/buildermark"
  license "MIT"
  version "VERSION"

  on_macos do
    on_arm do
      url "https://github.com/gelatinousdevelopment/buildermark/releases/download/vVERSION/buildermark_VERSION_darwin_arm64.tar.gz"
      sha256 "SHA256_DARWIN_ARM64"
    end

    on_intel do
      url "https://github.com/gelatinousdevelopment/buildermark/releases/download/vVERSION/buildermark_VERSION_darwin_amd64.tar.gz"
      sha256 "SHA256_DARWIN_AMD64"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/gelatinousdevelopment/buildermark/releases/download/vVERSION/buildermark_VERSION_linux_arm64.tar.gz"
      sha256 "SHA256_LINUX_ARM64"
    end

    on_intel do
      url "https://github.com/gelatinousdevelopment/buildermark/releases/download/vVERSION/buildermark_VERSION_linux_amd64.tar.gz"
      sha256 "SHA256_LINUX_AMD64"
    end
  end

  def install
    bin.install "buildermark"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/buildermark --version")
  end
end
