#!/usr/bin/env bash
#
# Publish a Buildermark release to GitHub using the GitHub CLI (gh).
#
# Reads artifacts from the release/<version>/ directory produced by
# build-release.sh and creates a GitHub release with all files attached.
#
# Usage:
#   ./scripts/publish-release.sh <version>
#   ./scripts/publish-release.sh 1.2.0
#   ./scripts/publish-release.sh 1.2.0 --draft
#
# Options:
#   --draft       Create the release as a draft (default: false)
#   --prerelease  Mark the release as a prerelease
#

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CHANGELOG="$ROOT_DIR/CHANGELOG.md"

DRAFT=""
PRERELEASE=""

# ---------------------------------------------------------------------------
# Parse arguments
# ---------------------------------------------------------------------------

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 <version> [--draft] [--prerelease]" >&2
    exit 1
fi

VERSION="$1"
shift

while [[ $# -gt 0 ]]; do
    case "$1" in
        --draft)      DRAFT="--draft"; shift ;;
        --prerelease) PRERELEASE="--prerelease"; shift ;;
        *)
            echo "Unknown argument: $1" >&2
            exit 1
            ;;
    esac
done

TAG="v$VERSION"
RELEASE_DIR="$ROOT_DIR/release/$VERSION"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

step() {
    echo ""
    echo "==> $1"
    echo ""
}

# ---------------------------------------------------------------------------
# Validate prerequisites
# ---------------------------------------------------------------------------

step "Validating prerequisites"

if ! command -v gh >/dev/null 2>&1; then
    echo "Error: GitHub CLI (gh) is not installed." >&2
    echo "  Install: brew install gh" >&2
    exit 1
fi

if ! gh auth status >/dev/null 2>&1; then
    echo "Error: Not authenticated with GitHub CLI." >&2
    echo "  Run: gh auth login" >&2
    exit 1
fi

if [[ ! -d "$RELEASE_DIR" ]]; then
    echo "Error: Release directory not found: $RELEASE_DIR" >&2
    echo "  Run build-release.sh first: ./scripts/build-release.sh $VERSION" >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Read release notes
# ---------------------------------------------------------------------------

step "Preparing release notes"

RELEASE_NOTES="$RELEASE_DIR/RELEASE_NOTES.md"
if [[ ! -f "$RELEASE_NOTES" ]]; then
    echo "Error: RELEASE_NOTES.md not found in $RELEASE_DIR" >&2
    echo "  This file should have been generated by build-release.sh." >&2
    exit 1
fi

echo "  Using release notes from: $RELEASE_NOTES"

# ---------------------------------------------------------------------------
# Collect artifacts (exclude the release notes and checksums text from upload)
# ---------------------------------------------------------------------------

step "Collecting artifacts"

ARTIFACTS=()
for f in "$RELEASE_DIR"/*; do
    case "$(basename "$f")" in
        RELEASE_NOTES.md) continue ;;
        *) ARTIFACTS+=("$f") ;;
    esac
done

if [[ ${#ARTIFACTS[@]} -eq 0 ]]; then
    echo "Error: No artifacts found in $RELEASE_DIR" >&2
    exit 1
fi

echo "  Found ${#ARTIFACTS[@]} artifact(s):"
for f in "${ARTIFACTS[@]}"; do
    echo "    $(basename "$f")"
done

# ---------------------------------------------------------------------------
# Create GitHub release
# ---------------------------------------------------------------------------

step "Creating GitHub release: $TAG"

gh release create "$TAG" \
    --title "Buildermark $TAG" \
    --notes-file "$RELEASE_NOTES" \
    $DRAFT \
    $PRERELEASE \
    "${ARTIFACTS[@]}"

step "Release published"
echo "  Tag:     $TAG"
echo "  URL:     $(gh release view "$TAG" --json url --jq '.url')"
